-- CreateEnum
CREATE TYPE "Role" AS ENUM ('ADMIN', 'PARTNER', 'MANAGER', 'COORDINATOR', 'BACKOFFICE', 'SUPERVISOR', 'SELLER');

-- AlterTable
ALTER TABLE "users" ADD COLUMN     "role" "Role" NOT NULL DEFAULT 'SELLER';
